"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-09 16:16:48.140466
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotation_revisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('annotation_id', sa.String(length=36), nullable=False),
    sa.Column('recording_id', sa.String(length=36), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('operation', sa.String(length=16), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('annotation_revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_annotation_revisions_annotation_id'), ['annotation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_annotation_revisions_recording_id'), ['recording_id'], unique=False)

    op.create_table('dataset_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('ontology_version', sa.String(length=32), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('manifest', sa.JSON(), nullable=False),
    sa.Column('archive_path', sa.String(length=500), nullable=False),
    sa.Column('archive_sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_table('datasets',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('license', sa.String(length=200), nullable=False),
    sa.Column('citation', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('annotation_semantics', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ontology_labels',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('level', sa.String(length=8), nullable=False),
    sa.Column('parent_code', sa.String(length=64), nullable=True),
    sa.Column('geometry', sa.String(length=16), nullable=False),
    sa.Column('tiers', sa.JSON(), nullable=False),
    sa.Column('attributes_schema', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('added_in_version', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['parent_code'], ['ontology_labels.code'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('ontology_meta',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('tiers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=False),
    sa.Column('level', sa.String(length=8), nullable=False),
    sa.Column('overlap_policy', sa.String(length=32), nullable=False),
    sa.Column('allow_free_labels', sa.Boolean(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('recordings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dataset_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('fs', sa.Float(), nullable=False),
    sa.Column('n_samples', sa.Integer(), nullable=False),
    sa.Column('leads', sa.JSON(), nullable=False),
    sa.Column('units', sa.JSON(), nullable=False),
    sa.Column('original_units', sa.JSON(), nullable=False),
    sa.Column('gains', sa.JSON(), nullable=False),
    sa.Column('patient_id', sa.String(length=100), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('signal_path', sa.String(length=500), nullable=False),
    sa.Column('signal_sha256', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_files', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id', 'name', name='uq_recording_dataset_name')
    )
    with op.batch_alter_table('recordings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recordings_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recordings_patient_id'), ['patient_id'], unique=False)

    op.create_table('annotations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('recording_id', sa.String(length=36), nullable=False),
    sa.Column('tier', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('lead', sa.String(length=32), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('start_sample', sa.Integer(), nullable=False),
    sa.Column('end_sample', sa.Integer(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('provenance', sa.JSON(), nullable=False),
    sa.Column('review_status', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('beat_id', sa.String(length=64), nullable=True),
    sa.Column('ontology_version', sa.String(length=32), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('annotations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_annotations_beat_id'), ['beat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_annotations_deleted'), ['deleted'], unique=False)
        batch_op.create_index('ix_annotations_rec_start', ['recording_id', 'start_sample'], unique=False)
        batch_op.create_index(batch_op.f('ix_annotations_recording_id'), ['recording_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_annotations_tier'), ['tier'], unique=False)

    op.create_table('prediction_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('recording_id', sa.String(length=36), nullable=False),
    sa.Column('algorithm', sa.String(length=100), nullable=False),
    sa.Column('algorithm_version', sa.String(length=32), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('lead', sa.String(length=32), nullable=True),
    sa.Column('start_sample', sa.Integer(), nullable=False),
    sa.Column('end_sample', sa.Integer(), nullable=False),
    sa.Column('experimental', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prediction_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prediction_runs_recording_id'), ['recording_id'], unique=False)

    op.create_table('annotation_relationships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('recording_id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('relation_type', sa.String(length=32), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['annotations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['annotations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('annotation_relationships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_annotation_relationships_recording_id'), ['recording_id'], unique=False)

    op.create_table('predictions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('recording_id', sa.String(length=36), nullable=False),
    sa.Column('tier', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('lead', sa.String(length=32), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('start_sample', sa.Integer(), nullable=False),
    sa.Column('end_sample', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('annotation_id', sa.String(length=36), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['prediction_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_predictions_recording_id'), ['recording_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_predictions_run_id'), ['run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_predictions_run_id'))
        batch_op.drop_index(batch_op.f('ix_predictions_recording_id'))

    op.drop_table('predictions')
    with op.batch_alter_table('annotation_relationships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_annotation_relationships_recording_id'))

    op.drop_table('annotation_relationships')
    with op.batch_alter_table('prediction_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prediction_runs_recording_id'))

    op.drop_table('prediction_runs')
    with op.batch_alter_table('annotations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_annotations_tier'))
        batch_op.drop_index(batch_op.f('ix_annotations_recording_id'))
        batch_op.drop_index('ix_annotations_rec_start')
        batch_op.drop_index(batch_op.f('ix_annotations_deleted'))
        batch_op.drop_index(batch_op.f('ix_annotations_beat_id'))

    op.drop_table('annotations')
    with op.batch_alter_table('recordings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recordings_patient_id'))
        batch_op.drop_index(batch_op.f('ix_recordings_dataset_id'))

    op.drop_table('recordings')
    op.drop_table('tiers')
    op.drop_table('ontology_meta')
    op.drop_table('ontology_labels')
    op.drop_table('datasets')
    op.drop_table('dataset_snapshots')
    with op.batch_alter_table('annotation_revisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_annotation_revisions_recording_id'))
        batch_op.drop_index(batch_op.f('ix_annotation_revisions_annotation_id'))

    op.drop_table('annotation_revisions')
    # ### end Alembic commands ###
